CREATE TABLE user (
    id INT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE band (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    year INT NOT NULL
);