basePath: /
definitions:
  dto.CreateBandParams:
    properties:
      name:
        type: string
      year:
        type: integer
    type: object
host: localhost:8000
info:
  contact:
    name: Artur Baccarin
  description: Band API for my personal project
  termsOfService: http://swagger.io/terms/
  title: API Band
  version: "1.0"
paths:
  /bands:
    post:
      consumes:
      - application/json
      description: Create bands
      parameters:
      - description: band request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBandParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      security:
      - ApiKeyAuth: []
      summary: Create band
      tags:
      - bands
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
