basePath: /
definitions:
  dto.CreateBandParams:
    properties:
      name:
        type: string
      year:
        type: integer
    type: object
  dto.UpdateBandParams:
    properties:
      name:
        type: string
      year:
        type: integer
    type: object
  entity.Band:
    properties:
      id:
        type: integer
      name:
        type: string
      year:
        type: integer
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: Artur Baccarin
  description: Band API for my personal project
  termsOfService: http://swagger.io/terms/
  title: API Band
  version: "1.0"
paths:
  /bands:
    post:
      consumes:
      - application/json
      parameters:
      - description: band request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBandParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a band
      tags:
      - band
  /bands/{ID}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: band ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete a band
      tags:
      - band
    get:
      consumes:
      - application/json
      parameters:
      - description: band ID
        in: path
        name: ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Band'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get a band
      tags:
      - band
    put:
      consumes:
      - application/json
      parameters:
      - description: band ID
        in: path
        name: ID
        required: true
        type: string
      - description: band request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateBandParams'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update a band
      tags:
      - band
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
